export * from './Category/CategoryCreatePage'
export * from './Category/CategoryPage'
export * from './AdminPage'
export * from './Product/ProductCreatePage'
export * from './Product/ProductPage'
export * from './Provier/ProveedorCreatePage'
export * from './Provier/ProveedoresPage'
export * from './HomePage'
